# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, to='albums.Album'),
        ),
    ]
